-- ---------------------------------------------------------------------------
-- Bring the `raw` and `time` module schemas up on an EXISTING database.
-- ---------------------------------------------------------------------------
-- GENERATED by scripts/generate-apply-modules.mjs from supabase/schema.sql.
-- Do not edit by hand: edit schema.sql and regenerate. A hand-maintained copy of
-- this much DDL is a second source of truth, and its drift surfaces only as a
-- production bug.
--
-- Why a separate file at all: schema.sql is not end-to-end idempotent. Section 1
-- creates the legacy netflix_users/files policies with no `if not exists` guard,
-- so re-running the whole file against a live database dies at the first policy
-- with 42710 "policy already exists" -- long before it reaches the module
-- sections. Sections 7 and 8 below ARE guarded and safe to re-run.
--
-- ---------------------------------------------------------------------------
-- STEP 1 of 2  Run this file in the Supabase SQL Editor.
--
-- STEP 2 of 2  Expose the schemas to PostgREST. Either route works.
--
--              (a) Dashboard -> Integrations -> Data API -> Settings ->
--                  "Exposed schemas". Set it to:
--                     public, graphql_public, raw, time
--                  NOTE the location moved: it used to live under Project
--                  Settings -> API, and Supabase's own docs still say so. On
--                  some projects it appears as Project Settings -> Data API.
--
--              (b) Or from SQL, if the dashboard control cannot be found:
--                     alter role authenticator
--                       set pgrst.db_schemas = 'public, graphql_public, raw, time';
--                     notify pgrst, 'reload config';
--                     notify pgrst, 'reload schema';
--                  Trade-off: setting this by hand takes exposed-schema
--                  management AWAY from the dashboard UI for this project.
--                  Undo with: alter role authenticator reset pgrst.db_schemas;
--                  The statement REPLACES the whole list, so public and
--                  graphql_public must stay in it or the rest of the app breaks.
--
--              Until the schemas are exposed every query answers 406 PGRST106
--              "Invalid schema", the query layer turns that into an empty result
--              by design, and /time shows "No time-tracking record linked to
--              your account" to every user while looking healthy.
--
--              PGRST106 rejects the schema NAME before it looks at any table, so
--              while it persists "the DDL landed" and "the DDL did not land" are
--              indistinguishable from any PostgREST client. Do not read it as
--              evidence that this file failed.
--
-- Verify both:  npm run check:live-ready
-- Background:   docs/architecture/MODULE-GO-LIVE.md
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- 7. raw — the connector landing zone
-- ---------------------------------------------------------------------------
-- First piece of the platform architecture (docs/architecture/PLATFORM-ARCHITECTURE.md
-- §1, §5). Deliberately the ONLY module schema created before discovery has run,
-- because it is the only one that cannot be wrong: it stores the vendor payload
-- verbatim as jsonb and makes no assumption about its shape. The typed `time`,
-- `projects` and `hr` schemas are written FROM the field inventories, not before
-- them -- that ordering is the whole point of the three-stage process.
--
-- Why land raw at all rather than transform on the way in:
--
--   * A transform bug is recoverable. If the parse was wrong we re-read from
--     `raw` instead of re-pulling from a vendor that rate-limits us and may no
--     longer hold the old value.
--   * It is the audit trail. "What did TrackingTime actually say on 3 March"
--     is answerable, which matters when a colleague disputes their hours.
--   * Vendors add and remove fields without warning. Verbatim capture means a
--     new field is already recorded by the time we notice it exists.
--
-- Append-only by construction: no update or delete policy is granted to anyone,
-- and writes arrive via the service role, which bypasses RLS entirely.

create schema if not exists raw;

-- Nobody reaches this schema through the API. Connectors use the service role
-- (which bypasses RLS and schema grants), and analysts read the typed layers.
revoke all on schema raw from anon, authenticated;

create table if not exists raw.vendor_record (
  id bigint generated always as identity primary key,

  -- Which system, which endpoint, which logical entity. `source` is
  -- deliberately free text rather than an enum: adding a vendor should not
  -- require a migration to the enum type first.
  source      text  not null check (source in ('trackingtime', 'asana', 'factorial', 'samdock')),
  entity      text  not null,
  endpoint    text  not null,

  -- The vendor's own id for this record, as text regardless of whether they
  -- issue integers or uuids. Never used as a join key across systems -- that is
  -- what platform.person and the identity maps are for. It exists so a re-sync
  -- can recognise the same record.
  source_id   text  not null,

  -- The workspace/account the record came from. TrackingTime and Asana both
  -- support a login belonging to several workspaces, and a payload is
  -- meaningless without knowing which one produced it.
  account_ref text,

  payload     jsonb not null,

  -- When we fetched it, not when the vendor changed it. Vendor timestamps live
  -- inside payload and are read during transform, where their timezone
  -- semantics can be dealt with explicitly.
  fetched_at  timestamptz not null default now(),

  -- A content hash of the payload. Lets a re-sync skip unchanged records
  -- without a deep compare, and makes "did this actually change" answerable.
  payload_hash text not null,

  -- Idempotency: re-running a sync must update-in-place rather than duplicate.
  -- Scoped by account_ref so the same id in two workspaces stays distinct.
  unique (source, entity, source_id, account_ref)
);

-- The two access patterns: "everything from this sync" and "history of this
-- one record".
create index if not exists vendor_record_source_entity_idx
  on raw.vendor_record (source, entity, fetched_at desc);

create index if not exists vendor_record_payload_idx
  on raw.vendor_record using gin (payload);

alter table raw.vendor_record enable row level security;

-- No policy is created on purpose. With RLS enabled and zero policies, every
-- API role is denied outright; only the service role (which bypasses RLS) can
-- read or write. Raw vendor payloads contain personal data and, from Factorial,
-- salary -- so the default is that nothing reaches a browser.

-- A record of each sync run, so "is the data stale" and "did last night's sync
-- actually finish" are answerable without reading the payload table.
create table if not exists raw.sync_run (
  id bigint generated always as identity primary key,
  source        text not null check (source in ('trackingtime', 'asana', 'factorial', 'samdock')),
  entity        text not null,
  started_at    timestamptz not null default now(),
  finished_at   timestamptz,

  -- Null finished_at with a non-null started_at means "still running or died".
  -- Distinguishing a crash from an empty result is the point of splitting these.
  status        text not null default 'running'
                check (status in ('running', 'ok', 'failed')),
  record_count  int,
  error_message text,

  -- The vendor's own paging cursor or high-water mark, so the next run can be
  -- incremental instead of re-reading everything.
  cursor_ref    text
);

create index if not exists sync_run_recent_idx
  on raw.sync_run (source, entity, started_at desc);

alter table raw.sync_run enable row level security;

-- Sync health is not sensitive and the Hub sync bar needs it, so this one is
-- readable -- but only the timing and status, never a payload.
--
-- Guarded like the `time` module policies below. Without the guard, applying the
-- module sections to an existing database succeeds the first time and fails the
-- second with 42710 "policy already exists" -- and whoever re-ran it has no way
-- to tell that error apart from a real problem. scripts/check-apply-modules.mjs
-- runs the extract twice and caught exactly this.
do $$
begin
  if not exists (select 1 from pg_policies where schemaname='raw' and tablename='sync_run'
                 and policyname='authenticated can read sync_run') then
    create policy "authenticated can read sync_run"
      on raw.sync_run for select to authenticated using (true);
  end if;
end $$;

grant usage on schema raw to authenticated;
grant select on raw.sync_run to authenticated;

-- service_role needs USAGE explicitly. It bypasses RLS but NOT schema
-- permissions, so without this the importer fails with 42501 "permission denied
-- for schema raw" -- which looks identical to the schema not existing. Measured
-- against live: every raw/time table returned 403 while public returned 200.
-- Table-level grants are applied at the end of this file, once every table in
-- both schemas exists.
grant usage on schema raw to service_role;


-- ---------------------------------------------------------------------------
-- 8. time -- the Time Tracking module
-- ---------------------------------------------------------------------------
-- The first typed module schema, written FROM the discovery field inventories
-- (docs/architecture/DISCOVERY-trackingtime.md), not from vendor documentation.
-- Every non-obvious decision below cites the measurement that forced it.
--
-- Why a schema rather than more public tables: PLATFORM-ARCHITECTURE.md §2. A
-- module client is pinned with supabase.schema('time'), so it physically cannot
-- reach another module's tables even by typo, while Hub still joins across all
-- of them in one query because it is one database.

create schema if not exists time;
grant usage on schema time to authenticated;

-- As for raw above: service_role bypasses RLS but not schema permissions, and
-- the TrackingTime importer writes with the service key.
grant usage on schema time to service_role;


-- Services -- the closest thing to HSE's real service catalogue that exists in
-- any vendor system. A small, stable vocabulary (~10 values observed).
--
-- is_travel/is_paid_travel are real columns rather than a string match on the
-- name. The vendor encodes the distinction in the label itself
-- ("Anfahrt & Abfahrt / Travelltime (Payed)" vs "(unpayed)"), which means any
-- report that needs it is one typo away from being wrong.
create table if not exists time.service (
  id             bigint generated always as identity primary key,
  source_id      text unique,                    -- TrackingTime service id, when imported
  name           text not null unique,
  is_travel      boolean not null default false,
  is_paid_travel boolean not null default false,
  is_internal    boolean not null default false,
  is_active      boolean not null default true,
  sort_order     int not null default 0,
  created_at     timestamptz not null default now(),

  -- Unpaid travel is still travel. Paid-but-not-travel is a contradiction.
  constraint paid_travel_is_travel check (not is_paid_travel or is_travel)
);


-- Customers. Deliberately thin: the CRM module owns the commercial record, this
-- is only what time tracking needs to attribute an hour.
create table if not exists time.customer (
  id          bigint generated always as identity primary key,
  source_id   text unique,
  name        text not null,
  is_archived boolean not null default false,
  -- 21 vendor custom fields exist and most are 100% null in the sample, so they
  -- are held verbatim rather than promoted to columns until one earns it.
  custom      jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

create unique index if not exists time_customer_name_idx on time.customer (lower(name));


create table if not exists time.project (
  id             bigint generated always as identity primary key,
  source_id      text unique,
  customer_id    bigint references time.customer(id) on delete set null,
  name           text not null,
  code           text,
  -- The Hub's own projects table is keyed by text id. Linking here rather than
  -- with an FK keeps the modules decoupled: `time` must not fail to insert
  -- because a Hub row has not been created yet.
  hub_project_id text,
  service_id     bigint references time.service(id) on delete set null,
  is_billable    boolean not null default true,
  is_archived    boolean not null default false,
  -- Observed as fractional HOURS on the vendor's project entity (0.833333),
  -- while events carry SECONDS. Same concept, different unit, different entity
  -- -- which is exactly why the unit is in the column name.
  estimated_hours numeric(10,2),
  custom         jsonb not null default '{}'::jsonb,
  created_at     timestamptz not null default now()
);

create index if not exists time_project_customer_idx on time.project (customer_id);


-- Tasks. Type matters more than it looks:
--
--   PERSONAL -- a real task somebody created. 70% billable.
--   GHOST    -- a calendar placeholder. 96.5% carry CALENDAR_SYNC_*, 98%
--               non-billable, and 1,508 of them collapse onto just 33 ids.
--
-- Measured over 4,189 live events: every one of the 1,427 events with neither a
-- customer nor a project is GHOST, and no PERSONAL event lacks a customer. That
-- is why time.entry.project_id is nullable and there is no "Internal"
-- pseudo-customer -- the absence is structural, not a tagging failure.
create table if not exists time.task (
  id            bigint generated always as identity primary key,
  source_id     text unique,
  project_id    bigint references time.project(id) on delete set null,
  name          text,
  task_type     text not null default 'PERSONAL' check (task_type in ('PERSONAL', 'GHOST')),
  is_archived   boolean not null default false,
  custom        jsonb not null default '{}'::jsonb,
  created_at    timestamptz not null default now()
);

create index if not exists time_task_project_idx on time.task (project_id);


-- A tracked person. Separate from public.people because the module owns its own
-- roster and must not break when Hub's identity map lags.
create table if not exists time.member (
  id             bigint generated always as identity primary key,
  source_id      text unique,
  email          text,
  display_name   text not null,
  hub_person_id  text,                            -- resolved to public.people.id
  user_id        uuid references auth.users(id) on delete set null,
  role           text not null default 'CO_WORKER'
                 check (role in ('ADMIN', 'MANAGER', 'PROJECT_MANAGER', 'CO_WORKER')),
  status         text not null default 'REGISTERED'
                 check (status in ('REGISTERED', 'VERIFIED', 'INVITED')),
  is_archived    boolean not null default false,
  -- Per-weekday contracted hours, observed on every vendor user
  -- (mon..fri: 8, sat/sun: 0). The honest denominator for utilisation.
  weekly_hours   numeric(5,2) not null default 40,
  created_at     timestamptz not null default now()
);

create unique index if not exists time_member_email_idx on time.member (lower(email))
  where email is not null;
create index if not exists time_member_user_idx on time.member (user_id);


-- Rates, effective-dated from day one.
--
-- The vendor carries a single current hourly_rate/hourly_cost per user with no
-- history. Re-costing last year at this year's rate is simply wrong, and the
-- history cannot be reconstructed after the fact -- so the table is dated now
-- even though the first import will write one open-ended row per member.
create table if not exists time.member_rate (
  id           bigint generated always as identity primary key,
  member_id    bigint not null references time.member(id) on delete cascade,
  hourly_rate  numeric(10,2),                     -- what the client is charged
  hourly_cost  numeric(10,2),                     -- what the person costs us
  currency     text not null default 'EUR',
  valid_from   date not null default current_date,
  valid_to     date,                              -- null = currently in force

  constraint rate_dates_ordered check (valid_to is null or valid_to > valid_from)
);

create index if not exists time_member_rate_lookup_idx
  on time.member_rate (member_id, valid_from desc);


-- The entry. One tracked interval -- the table this whole module is about.
create table if not exists time.entry (
  id               bigint generated always as identity primary key,
  source_id        text unique,                   -- vendor event id, null for entries we created

  member_id        bigint not null references time.member(id) on delete restrict,
  task_id          bigint references time.task(id) on delete set null,
  project_id       bigint references time.project(id) on delete set null,
  customer_id      bigint references time.customer(id) on delete set null,
  service_id       bigint references time.service(id) on delete set null,

  started_at       timestamptz not null,
  ended_at         timestamptz,                   -- null while a timer is running

  -- SECONDS. Proved arithmetically, not assumed: across 800 sampled live events
  -- (End - Start) equalled Duration exactly 800/800 times. This repo already
  -- stores Factorial in minutes and TrackingTime in seconds, so the unit is in
  -- the column name deliberately -- never call this column `hours`.
  duration_seconds integer,

  is_billable      boolean not null default true,
  is_billed        boolean not null default false,
  notes            text,
  timezone         text,

  -- Where the row came from. GHOST/calendar time is kept rather than discarded,
  -- but it is distinguishable so utilisation can exclude it deliberately.
  source_system    text not null default 'manual'
                   check (source_system in ('manual', 'timer', 'trackingtime', 'calendar')),
  is_calendar      boolean not null default false,

  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),

  -- A finished entry must have a coherent interval. A running timer (ended_at
  -- null) is exempt -- that is the one legitimate open state.
  constraint entry_interval_ordered check (ended_at is null or ended_at >= started_at),
  constraint entry_duration_nonneg  check (duration_seconds is null or duration_seconds >= 0),
  -- A finished entry must know how long it was.
  constraint entry_finished_has_duration
    check (ended_at is null or duration_seconds is not null)
);

create index if not exists time_entry_member_start_idx on time.entry (member_id, started_at desc);
create index if not exists time_entry_project_idx      on time.entry (project_id, started_at desc);
create index if not exists time_entry_customer_idx     on time.entry (customer_id, started_at desc);
create index if not exists time_entry_started_idx      on time.entry (started_at desc);

-- At most one running timer per member. A partial unique index is the only way
-- to express this that a concurrent second insert cannot slip past.
create unique index if not exists time_entry_one_running_per_member
  on time.entry (member_id) where ended_at is null;


-- Which time.member is the caller. security definer for the same reason as the
-- public helpers: a policy on time.entry that reads time.member inside its own
-- USING clause recurses through RLS unpredictably.
create or replace function time.current_member_id()
returns bigint
language sql stable security definer set search_path = time, public
as $$
  select m.id from time.member m
  where m.user_id = auth.uid()
     or (m.hub_person_id is not null and m.hub_person_id = app_user_person_id())
  limit 1;
$$;

-- Can the caller see this member's time? Mirrors can_view_person(): exec sees
-- all, dept_head sees their department via the Hub person link, everyone sees
-- their own.
create or replace function time.can_view_member(target_member_id bigint)
returns boolean
language sql stable security definer set search_path = time, public
as $$
  select
    app_user_role() = 'exec'
    or target_member_id = time.current_member_id()
    or exists (
      select 1 from time.member m
      where m.id = target_member_id
        and m.hub_person_id is not null
        and can_view_person(m.hub_person_id)
    );
$$;

revoke execute on function time.current_member_id(), time.can_view_member(bigint)
  from public, anon;
grant execute on function time.current_member_id(), time.can_view_member(bigint)
  to authenticated;


alter table time.service     enable row level security;
alter table time.customer    enable row level security;
alter table time.project     enable row level security;
alter table time.task        enable row level security;
alter table time.member      enable row level security;
alter table time.member_rate enable row level security;
alter table time.entry       enable row level security;

-- Guarded so re-running the whole file is silent rather than erroring on a
-- policy that already exists.
do $$
begin
  -- Reference data: any signed-in colleague needs to pick from these to log time.
  if not exists (select 1 from pg_policies where schemaname='time' and tablename='service'
                 and policyname='authenticated can read service') then
    create policy "authenticated can read service" on time.service
      for select to authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname='time' and tablename='customer'
                 and policyname='authenticated can read customer') then
    create policy "authenticated can read customer" on time.customer
      for select to authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname='time' and tablename='project'
                 and policyname='authenticated can read project') then
    create policy "authenticated can read project" on time.project
      for select to authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname='time' and tablename='task'
                 and policyname='authenticated can read task') then
    create policy "authenticated can read task" on time.task
      for select to authenticated using (true);
  end if;

  -- Only someone who can manage projects reshapes the catalogue.
  if not exists (select 1 from pg_policies where schemaname='time' and tablename='project'
                 and policyname='project writers can manage project') then
    create policy "project writers can manage project" on time.project
      for all to authenticated
      using (app_user_has_permission('projects:write'))
      with check (app_user_has_permission('projects:write'));
  end if;

  if not exists (select 1 from pg_policies where schemaname='time' and tablename='customer'
                 and policyname='project writers can manage customer') then
    create policy "project writers can manage customer" on time.customer
      for all to authenticated
      using (app_user_has_permission('projects:write'))
      with check (app_user_has_permission('projects:write'));
  end if;

  if not exists (select 1 from pg_policies where schemaname='time' and tablename='task'
                 and policyname='project writers can manage task') then
    create policy "project writers can manage task" on time.task
      for all to authenticated
      using (app_user_has_permission('projects:write'))
      with check (app_user_has_permission('projects:write'));
  end if;

  if not exists (select 1 from pg_policies where schemaname='time' and tablename='service'
                 and policyname='project writers can manage service') then
    create policy "project writers can manage service" on time.service
      for all to authenticated
      using (app_user_has_permission('projects:write'))
      with check (app_user_has_permission('projects:write'));
  end if;

  -- Roster: visible to whoever may see that person's time.
  if not exists (select 1 from pg_policies where schemaname='time' and tablename='member'
                 and policyname='scoped read of member') then
    create policy "scoped read of member" on time.member
      for select to authenticated using (time.can_view_member(id));
  end if;

  if not exists (select 1 from pg_policies where schemaname='time' and tablename='member'
                 and policyname='user admins can manage member') then
    create policy "user admins can manage member" on time.member
      for all to authenticated
      using (app_user_has_permission('admin:users:write'))
      with check (app_user_has_permission('admin:users:write'));
  end if;

  -- Rates are commercially sensitive: hourly_cost is what a colleague costs the
  -- company. Own rate, or exec. Deliberately NOT visible to dept_head, who can
  -- otherwise see their department's time.
  if not exists (select 1 from pg_policies where schemaname='time' and tablename='member_rate'
                 and policyname='own rate or exec can read member_rate') then
    create policy "own rate or exec can read member_rate" on time.member_rate
      for select to authenticated
      using (app_user_role() = 'exec' or member_id = time.current_member_id());
  end if;

  if not exists (select 1 from pg_policies where schemaname='time' and tablename='member_rate'
                 and policyname='exec can manage member_rate') then
    create policy "exec can manage member_rate" on time.member_rate
      for all to authenticated
      using (app_user_role() = 'exec')
      with check (app_user_role() = 'exec');
  end if;

  -- Entries: read what you are allowed to see.
  --
  -- WHY THIS IS WRITTEN AS THREE OR'D BRANCHES rather than the one call to
  -- time.can_view_member(member_id) it replaces, which read far better:
  --
  -- MEASURED on the live project (scripts/check-rls-hoisting.mjs), fetching the
  -- same 4,194 entries the TrackingTime dashboard reads:
  --
  --     as service_role, RLS bypassed      311ms
  --     as a real exec, RLS applied      2,870ms
  --
  -- 2.5s of policy evaluation, and it SCALED with rows scanned (~55ms for a month,
  -- ~170ms per 1000 rows) which is the signature of a per-row predicate. The cause
  -- is that can_view_member takes a per-ROW argument: it is STABLE, but a stable
  -- function whose input varies per row must be called per row -- 4,194 times, each
  -- invoking app_user_role(), which itself reads app_user_profile.
  --
  -- The first two branches below do not depend on the row at all. Wrapping each in
  -- a scalar subquery lets the planner evaluate it ONCE per statement as an
  -- InitPlan (this is Supabase's documented RLS performance pattern), and because
  -- `or` short-circuits, an exec never reaches the per-row branch at all.
  --
  -- SEMANTICS ARE UNCHANGED, and that is checkable rather than asserted:
  -- can_view_member is literally `app_user_role() = 'exec' OR target = current_member_id()
  -- OR exists(department check)`. Hoisting the first two disjuncts out of the
  -- function and leaving the third to the function computes the same boolean --
  -- `A or B or f(row)` where f = `A or B or C`. The third branch still goes through
  -- can_view_member, so the department rule has exactly one implementation.
  --
  -- The RLS gates (npm run test:time-rls, test:rls, test:rls-control) cover the
  -- access outcomes and must pass unchanged; this is a performance rewrite and any
  -- behaviour difference is a bug, not a trade-off.
  if not exists (select 1 from pg_policies where schemaname='time' and tablename='entry'
                 and policyname='scoped read of entry') then
    create policy "scoped read of entry" on time.entry
      for select to authenticated using (
        (select app_user_role()) = 'exec'
        or member_id = (select time.current_member_id())
        or time.can_view_member(member_id)
      );
  end if;

  -- Write only your OWN time. member_id is pinned to the caller in WITH CHECK,
  -- so an entry cannot be filed under a colleague even by a crafted request.
  if not exists (select 1 from pg_policies where schemaname='time' and tablename='entry'
                 and policyname='own entry insert') then
    create policy "own entry insert" on time.entry
      for insert to authenticated
      with check (
        member_id = time.current_member_id()
        and app_user_has_permission('timesheets:write')
      );
  end if;

  if not exists (select 1 from pg_policies where schemaname='time' and tablename='entry'
                 and policyname='own entry update') then
    create policy "own entry update" on time.entry
      for update to authenticated
      using (member_id = time.current_member_id() and not is_billed)
      with check (member_id = time.current_member_id());
  end if;

  -- An invoiced entry is not deletable by its owner -- that is the point of
  -- is_billed. Exec can still correct a mistake.
  if not exists (select 1 from pg_policies where schemaname='time' and tablename='entry'
                 and policyname='own entry delete') then
    create policy "own entry delete" on time.entry
      for delete to authenticated
      using (
        (member_id = time.current_member_id() and not is_billed)
        or app_user_role() = 'exec'
      );
  end if;
end $$;

grant select on time.service, time.customer, time.project, time.task, time.member, time.member_rate
  to authenticated;
grant select, insert, update, delete on time.entry to authenticated;
grant insert, update, delete on time.service, time.customer, time.project, time.task, time.member,
  time.member_rate to authenticated;
grant usage, select on all sequences in schema time to authenticated;


-- A row per member per ISO week: logged, billable, and the contracted
-- denominator. security_invoker so the caller's RLS still applies -- without it
-- this view would be a hole straight through time.entry's policies.
create or replace view time.week_summary
with (security_invoker = true) as
select
  e.member_id,
  m.display_name,
  m.hub_person_id,
  date_trunc('week', e.started_at)::date                             as week_start,
  sum(e.duration_seconds)                                            as total_seconds,
  sum(e.duration_seconds) filter (where e.is_billable)               as billable_seconds,
  -- GHOST/calendar time is real time but usually not deliberate work, so it is
  -- reported separately rather than silently inflating utilisation.
  sum(e.duration_seconds) filter (where e.is_calendar)               as calendar_seconds,
  count(*)                                                           as entry_count,
  m.weekly_hours * 3600                                              as contracted_seconds
from time.entry e
join time.member m on m.id = e.member_id
where e.duration_seconds is not null
group by e.member_id, m.display_name, m.hub_person_id, date_trunc('week', e.started_at), m.weekly_hours;

grant select on time.week_summary to authenticated;


-- ---------------------------------------------------------------------------
-- 8b. Analytics views for the organisation dashboard
--
-- Two rules govern everything below, and both were established empirically
-- rather than assumed:
--
--   1. MONEY IS NOT A VIEW. A security_invoker view that joins time.member_rate
--      does not fail closed for a caller who cannot see every rate -- it fails
--      PARTIAL. Measured in PGlite: on a project with three members and true
--      revenue of 300.00, a dept_head who could see exactly one rate row got
--      back "90.00". A plausible wrong number is worse than an error, because
--      nothing about it looks broken. Every money figure therefore comes from
--      time.project_economics(), a security definer function gated on a
--      permission, which returns zero rows rather than a partial total.
--
--   2. CALENDAR TIME IS REPORTED, NEVER SILENTLY MIXED IN. 46% of live events
--      (40% of logged hours) are GHOST calendar placeholders, most with no
--      customer and no project -- measured, and higher than the 34% previously
--      recorded here. Folding
--      them into a utilisation or billable figure would make that figure
--      meaningless, so every view carries calendar_seconds as its own column
--      and the deliberate-work total excludes it.
--
-- Unit discipline: time.entry.duration_seconds is SECONDS, while
-- time.project.estimated_hours is HOURS. Every crossing of that boundary below
-- is written as `seconds / 3600.0` with a float divisor -- integer division
-- would truncate 3599 seconds to 0 hours.
-- ---------------------------------------------------------------------------

-- Organisation-wide weekly totals. The dashboard's trend line.
--
-- count(distinct member_id) rather than count(*) so a week where one person
-- logged forty entries does not read as forty active people.
create or replace view time.org_week
with (security_invoker = true) as
select
  date_trunc('week', e.started_at)::date                        as week_start,
  coalesce(sum(e.duration_seconds), 0)                          as total_seconds,
  coalesce(sum(e.duration_seconds) filter (where e.is_billable), 0)  as billable_seconds,
  coalesce(sum(e.duration_seconds) filter (where e.is_calendar), 0)  as calendar_seconds,
  -- Deliberate work: what a human chose to track, excluding calendar noise.
  coalesce(sum(e.duration_seconds) filter (where not e.is_calendar), 0) as tracked_seconds,
  count(*)                                                      as entry_count,
  count(distinct e.member_id)                                   as active_members,
  count(distinct e.project_id)                                  as active_projects
from time.entry e
where e.duration_seconds is not null
group by date_trunc('week', e.started_at);

grant select on time.org_week to authenticated;


-- Per-project rollup. Hours only -- no rates, so it is safe for anyone whose
-- RLS lets them see the underlying entries.
--
-- LEFT JOIN from project, so a project with no time logged still appears with
-- zeroes. An inner join would hide exactly the projects worth asking about.
create or replace view time.project_summary
with (security_invoker = true) as
select
  p.id                                                          as project_id,
  p.name                                                        as project_name,
  p.is_billable,
  p.is_archived,
  c.id                                                          as customer_id,
  c.name                                                        as customer_name,
  p.estimated_hours,
  coalesce(sum(e.duration_seconds), 0)                          as total_seconds,
  coalesce(sum(e.duration_seconds) filter (where e.is_billable), 0) as billable_seconds,
  coalesce(sum(e.duration_seconds) filter (where e.is_calendar), 0) as calendar_seconds,
  -- count(e.id) not count(*): the LEFT JOIN produces one all-null row for a
  -- project with no entries, and count(*) would report that as 1.
  count(e.id)                                                   as entry_count,
  count(distinct e.member_id)                                   as member_count,
  max(e.started_at)                                             as last_activity_at,
  -- Budget burn. estimated_hours is HOURS, duration_seconds is SECONDS.
  -- nullif guards a zero or absent estimate: "no budget set" must read as
  -- unknown, not as 0% or a division error.
  case
    when coalesce(p.estimated_hours, 0) > 0
    then round((coalesce(sum(e.duration_seconds), 0) / 3600.0)
               / nullif(p.estimated_hours, 0) * 100, 1)
  end                                                           as burn_percent
from time.project p
left join time.customer c on c.id = p.customer_id
left join time.entry e    on e.project_id = p.id and e.duration_seconds is not null
group by p.id, p.name, p.is_billable, p.is_archived, c.id, c.name, p.estimated_hours;

grant select on time.project_summary to authenticated;


-- Per-customer rollup. Same hours-only safety as project_summary.
--
-- The project count is a SCALAR SUBQUERY, not a second LEFT JOIN, and that is
-- not a stylistic preference. Joining customer to both project and entry
-- fans out: N projects x M entries produces N*M rows, so every sum() is
-- multiplied by the project count. Measured before this was fixed -- a customer
-- with 2 projects and 4 entries reported 8 entries and exactly double the
-- hours. The bug hid because count(distinct p.id) was still correct, so the
-- one column anyone would sanity-check looked fine while the hours lied.
create or replace view time.customer_summary
with (security_invoker = true) as
select
  c.id                                                          as customer_id,
  c.name                                                        as customer_name,
  c.is_archived,
  coalesce(sum(e.duration_seconds), 0)                          as total_seconds,
  coalesce(sum(e.duration_seconds) filter (where e.is_billable), 0) as billable_seconds,
  (select count(*) from time.project p where p.customer_id = c.id) as project_count,
  count(e.id)                                                   as entry_count,
  max(e.started_at)                                             as last_activity_at
from time.customer c
left join time.entry e on e.customer_id = c.id and e.duration_seconds is not null
group by c.id, c.name, c.is_archived;

grant select on time.customer_summary to authenticated;


-- Per-service rollup. This is the closest thing to HSE's real service
-- catalogue, so "which service actually consumes our week" is a first-class
-- question rather than a drill-down.
create or replace view time.service_summary
with (security_invoker = true) as
select
  s.id                                                          as service_id,
  s.name                                                        as service_name,
  s.is_travel,
  s.is_paid_travel,
  s.is_internal,
  coalesce(sum(e.duration_seconds), 0)                          as total_seconds,
  coalesce(sum(e.duration_seconds) filter (where e.is_billable), 0) as billable_seconds,
  count(e.id)                                                   as entry_count
from time.service s
left join time.entry e on e.service_id = s.id and e.duration_seconds is not null
group by s.id, s.name, s.is_travel, s.is_paid_travel, s.is_internal;

grant select on time.service_summary to authenticated;


-- Per-member utilisation over a rolling window.
--
-- Deliberately NOT joined to member_rate: this view answers "how busy is this
-- person", and adding cost would drag the whole thing behind the exec gate for
-- no benefit. Utilisation uses tracked_seconds (calendar excluded), because a
-- day of synced meetings is not a day of billable capacity.
--
-- BOUNDED AT TODAY, and that is not an edge case. TrackingTime stores PLANNED
-- entries months ahead -- 19 of 53 weeks in live data are future-dated. Without
-- the bound this view reported planned work as logged: People showed 8.263h
-- against the Overview's bounded 7.592h, 671h (9%) apart one click apart, with
-- one person reading 1.154h against 694h actually worked and a "last active"
-- date of 2026-12-31. It corrupts utilisation as well as totals, since unworked
-- time inflates both tracked_seconds and weeks_active.
--
-- The bound belongs in the JOIN, not a WHERE clause. This is a LEFT JOIN, and in
-- WHERE the predicate would drop every member with no qualifying entry --
-- measured: the roster collapses from 49 to 18, hiding everyone who has not
-- logged time. In the join condition those members are kept with zeroed sums.
--
-- Guarded by npm run check:people-overview-agree.
create or replace view time.member_utilisation
with (security_invoker = true) as
select
  m.id                                                          as member_id,
  m.display_name,
  m.hub_person_id,
  m.is_archived,
  m.weekly_hours,
  coalesce(sum(e.duration_seconds), 0)                          as total_seconds,
  coalesce(sum(e.duration_seconds) filter (where e.is_billable), 0) as billable_seconds,
  coalesce(sum(e.duration_seconds) filter (where e.is_calendar), 0) as calendar_seconds,
  coalesce(sum(e.duration_seconds) filter (where not e.is_calendar), 0) as tracked_seconds,
  count(e.id)                                                   as entry_count,
  count(distinct date_trunc('week', e.started_at))              as weeks_active,
  max(e.started_at)                                             as last_activity_at
from time.member m
left join time.entry e
  on e.member_id = m.id
 and e.duration_seconds is not null
 and e.started_at::date <= current_date
group by m.id, m.display_name, m.hub_person_id, m.is_archived, m.weekly_hours;

grant select on time.member_utilisation to authenticated;


-- Money. A function, not a view, and the difference is the whole point.
--
-- security definer means the rate join runs with the owner's rights, so the
-- total is always complete -- there is no partial-aggregate failure mode. The
-- guard is an explicit permission check that returns zero rows for anyone
-- without it, which is a visibly empty result rather than a quietly wrong one.
--
-- The rate join is effective-dated on the ENTRY's date, not today's: re-costing
-- last year's work at this year's rate produces a confident wrong answer.
-- LEFT JOIN, so an entry whose member has no rate row still contributes its
-- hours and simply adds nothing to revenue -- an inner join would silently drop
-- those hours and understate the project.
create or replace function time.project_economics(
  p_from date default null,
  p_to   date default null
)
returns table (
  project_id       bigint,
  project_name     text,
  customer_name    text,
  total_seconds    bigint,
  billable_seconds bigint,
  revenue          numeric,
  cost             numeric,
  margin           numeric,
  margin_percent   numeric
)
language sql stable security definer set search_path = time, public
as $$
  select
    p.id,
    coalesce(p.name, '(no project)'),
    c.name,
    coalesce(sum(e.duration_seconds), 0)::bigint,
    coalesce(sum(e.duration_seconds) filter (where e.is_billable), 0)::bigint,
    round(coalesce(sum(
      case when e.is_billable
           then e.duration_seconds / 3600.0 * coalesce(r.hourly_rate, 0)
           else 0 end), 0), 2),
    round(coalesce(sum(e.duration_seconds / 3600.0 * coalesce(r.hourly_cost, 0)), 0), 2),
    round(coalesce(sum(
      case when e.is_billable
           then e.duration_seconds / 3600.0 * coalesce(r.hourly_rate, 0)
           else 0 end), 0)
      - coalesce(sum(e.duration_seconds / 3600.0 * coalesce(r.hourly_cost, 0)), 0), 2),
    case
      when coalesce(sum(
        case when e.is_billable
             then e.duration_seconds / 3600.0 * coalesce(r.hourly_rate, 0)
             else 0 end), 0) > 0
      then round((coalesce(sum(
             case when e.is_billable
                  then e.duration_seconds / 3600.0 * coalesce(r.hourly_rate, 0)
                  else 0 end), 0)
           - coalesce(sum(e.duration_seconds / 3600.0 * coalesce(r.hourly_cost, 0)), 0))
           / nullif(coalesce(sum(
             case when e.is_billable
                  then e.duration_seconds / 3600.0 * coalesce(r.hourly_rate, 0)
                  else 0 end), 0), 0) * 100, 1)
    end
  from time.entry e
  -- LEFT, not INNER. 2,205 of 5,218 live entries carry no project_id, and an
  -- inner join dropped every one of them from the only panel that reports cost
  -- -- so economics and the totals strip disagreed about the same period (866.9h
  -- against 649h for July) with nothing on screen to explain the difference.
  -- Unattributed time still costs money: a member rate times hours worked is
  -- spend the business incurred whether or not anyone filed it against a
  -- project, and hiding it flatters every margin on the page. It surfaces as a
  -- single "(no project)" row with a null project_id, which the UI renders
  -- unlinked because there is no record to open.
  left join time.project p on p.id = e.project_id
  left join time.customer c on c.id = p.customer_id
  left join time.member_rate r
         on r.member_id = e.member_id
        and e.started_at::date >= r.valid_from
        and (r.valid_to is null or e.started_at::date < r.valid_to)
  where app_user_has_permission('overview:export')
    and e.duration_seconds is not null
    and (p_from is null or e.started_at::date >= p_from)
    and (p_to   is null or e.started_at::date <= p_to)
  group by p.id, p.name, c.name;
$$;

revoke execute on function time.project_economics(date, date) from public, anon;
grant  execute on function time.project_economics(date, date) to authenticated;


-- Seed the service catalogue observed in the live account. on conflict do
-- nothing so a re-run never disturbs edits made in the app.
insert into time.service (name, is_travel, is_paid_travel, is_internal, sort_order) values
  ('DGUV V2: Sifa / Safety Engeineer',            false, false, false, 10),
  ('DGUV V2: Betriebsarzt / Company doctor',      false, false, false, 20),
  ('SiGeKo / construction coordination',          false, false, false, 30),
  ('Brandschutzhelfer',                           false, false, false, 40),
  ('Brandschutzbeauftragter (Fire Safety Officer)', false, false, false, 45),
  ('Risk Assessment',                             false, false, false, 50),
  ('Grundunterweisung / Trainingsacademy',        false, false, false, 60),
  ('Projekt: Health & Safety Consulting',         false, false, false, 70),
  ('Anfahrt & Abfahrt / Travelltime (Payed)',     true,  true,  false, 80),
  ('Anfahrt & Abfahrt / Travelltime (unpayed)',   true,  false, false, 90),
  ('intern',                                      false, false, true, 100)
on conflict (name) do nothing;


-- ---------------------------------------------------------------------------
-- The forward references promised in section 2. project_sections and
-- project_tasks each carry an optional time_project_id, but they are declared
-- ~1,300 lines above time.project, so the constraints could not be inline: a
-- fresh run of this file would have died on a table that did not exist yet.
--
-- ON DELETE CASCADE matches the Hub-side parent: deleting a project takes its
-- board with it rather than leaving orphaned columns and tasks pointing at
-- nothing. Guarded with a DO block so re-running the file is safe -- Postgres
-- has no "add constraint if not exists".
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'project_sections_time_project_fk'
  ) then
    alter table public.project_sections
      add constraint project_sections_time_project_fk
      foreign key (time_project_id) references time.project(id) on delete cascade;
  end if;
  if not exists (
    select 1 from pg_constraint where conname = 'project_tasks_time_project_fk'
  ) then
    alter table public.project_tasks
      add constraint project_tasks_time_project_fk
      foreign key (time_project_id) references time.project(id) on delete cascade;
  end if;
end $$;

create index if not exists project_sections_time_project_idx
  on public.project_sections (time_project_id, position);
create index if not exists project_tasks_time_project_idx
  on public.project_tasks (time_project_id, sort_order);


-- 9. Module schema grants for service_role
-- ---------------------------------------------------------------------------
-- Deliberately last: `grant all on all tables in schema` resolves the table
-- list at execution time, so it must run after every table above exists.
--
-- Why this is needed at all: service_role bypasses RLS, which makes it easy to
-- assume it bypasses everything. It does not -- schema and table permissions
-- still apply. Without these grants the TrackingTime importer fails with
-- 42501 "permission denied for schema time", which reads exactly like the
-- schema not existing and sends you looking in the wrong place. Measured
-- against live: every raw.* and time.* probe returned 403 while public
-- returned 200.
--
-- The `alter default privileges` lines cover tables added later, so a new
-- module table does not silently break the importer.

grant all on all tables    in schema raw  to service_role;
grant all on all sequences in schema raw  to service_role;
alter default privileges in schema raw  grant all on tables    to service_role;
alter default privileges in schema raw  grant all on sequences to service_role;

grant all on all tables    in schema time to service_role;
grant all on all sequences in schema time to service_role;
alter default privileges in schema time grant all on tables    to service_role;
alter default privileges in schema time grant all on sequences to service_role;
