-- ---------------------------------------------------------------------------
-- CONVENIENCE EXTRACT -- run this once against the live database.
--
-- supabase/schema.sql REMAINS THE SOURCE OF TRUTH. This file is a verbatim
-- copy of the parts of it that are missing from live (schema.sql §3b plus the
-- matching seed rows from §5), pulled out so you can paste a short script
-- instead of 1,444 lines.
--
-- Do NOT edit this file to change behaviour. Edit schema.sql and re-extract,
-- otherwise the two drift -- which is exactly the failure that put us here:
-- the permission system lived only in a standalone migration, schema.sql got
-- applied to live, and the migration did not.
--
-- Verified missing from live before writing this (all 404):
--   app_permission, app_role_permission, app_module, platform_decision,
--   app_user_has_permission(), app_user_modules()
-- Present and untouched by this script: the 21 tables already live.
--
-- Safe to re-run: create table if not exists / create or replace function /
-- on conflict do nothing throughout. The policies use a guarded DO block so a
-- second run does not error on "policy already exists".
-- ---------------------------------------------------------------------------


-- ===========================================================================
-- 1. Tables
-- ===========================================================================

-- Permission catalogue -- one row per discrete capability.
-- permission_key is 'module:resource:action' or the older 'resource:action'.
-- Both shapes coexist deliberately: the pre-module keys (overview:read,
-- people:read_all) are still what the current app checks, and renaming them
-- would be a breaking change for no gain. New module work uses the 3-part form.
create table if not exists app_permission (
  permission_key text primary key,
  display_name   text not null,
  resource       text not null,
  action         text not null,
  description    text,
  -- Which module owns this capability. Drives bridge-portal tile visibility.
  module_key     text not null default 'hub',
  sort_order     int  not null default 0
);

alter table app_permission enable row level security;

create table if not exists app_role_permission (
  role_key       text not null references app_role(role_key) on delete cascade,
  permission_key text not null references app_permission(permission_key) on delete cascade,
  granted_at     timestamptz not null default now(),
  primary key (role_key, permission_key)
);

alter table app_role_permission enable row level security;

-- Module registry -- the bridge portal's tile list lives in data, not code.
-- A tile is shown when the signed-in user holds ANY permission belonging to
-- that module, so granting a permission is the only step needed to reveal a
-- module. There is deliberately no hardcoded tile array in the app.
create table if not exists app_module (
  module_key   text primary key,
  display_name text not null,
  tagline      text,
  -- Route the tile links to. Null means "built but not routed yet".
  href         text,
  accent       text not null default '#91C2B7',
  -- false keeps a module in the catalogue but hides its tile from everyone,
  -- regardless of permissions. Used for modules that are planned, not live.
  is_live      boolean not null default false,
  sort_order   int not null default 0
);

alter table app_module enable row level security;

-- Hub's only write surface. Hub is otherwise read-only across every module;
-- managerial acts (approve overtime, approve leave, acknowledge an overrun)
-- land here and the owning module reads and applies them.
--
-- subject_ref is text, not a foreign key, precisely because it points into
-- different modules' tables ('timesheet_entry:412', 'leave_request:88').
create table if not exists platform_decision (
  id           bigserial primary key,
  kind         text not null,
  subject_ref  text not null,
  outcome      text not null check (outcome in ('approved', 'rejected', 'acknowledged')),
  note         text,
  decided_by   uuid not null references auth.users(id) on delete restrict,
  decided_at   timestamptz not null default now()
);

alter table platform_decision enable row level security;

create index if not exists platform_decision_subject_idx
  on platform_decision (subject_ref);


-- ===========================================================================
-- 2. Functions
--
-- Must be defined BEFORE the policies below: Postgres resolves function
-- references in a policy expression at CREATE POLICY time, so a policy cannot
-- reference a function defined later in the same script.
-- ===========================================================================

-- Single entry point for every permission check in app code.
-- security definer so it can read app_user_profile without tripping RLS
-- recursion, matching the five helpers already live.
--
-- Inherits the is_active check transitively: app_user_role() filters on
-- is_active, so a deactivated profile resolves to no role and holds no
-- permissions.
create or replace function app_user_has_permission(p_key text)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1
    from app_role_permission rp
    where rp.role_key = app_user_role()
      and rp.permission_key = p_key
  );
$$;

-- Which modules should this user see on the bridge portal? Kept in SQL rather
-- than the app so the tile list cannot drift from the permission data.
create or replace function app_user_modules()
returns setof app_module
language sql stable security definer set search_path = public
as $$
  select m.*
  from app_module m
  where m.is_live
    and exists (
      select 1
      from app_role_permission rp
      join app_permission p on p.permission_key = rp.permission_key
      where rp.role_key = app_user_role()
        and p.module_key = m.module_key
    )
  order by m.sort_order, m.display_name;
$$;

revoke execute on function app_user_has_permission(text), app_user_modules()
  from public, anon;
grant  execute on function app_user_has_permission(text), app_user_modules()
  to authenticated;


-- ===========================================================================
-- 3. Policies
--
-- Wrapped in a guarded DO block. schema.sql uses plain CREATE POLICY, which
-- errors on a second run; here the guard makes re-running silent.
-- ===========================================================================

do $$
begin
  -- Permissions, role maps and the module registry are readable by every
  -- authenticated user: the portal needs them to decide which tiles to render,
  -- and requirePermission() needs them on every gated request. Only execs write.

  if not exists (select 1 from pg_policies
                 where tablename = 'app_permission'
                   and policyname = 'authenticated can read app_permission') then
    create policy "authenticated can read app_permission"
      on app_permission for select to authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies
                 where tablename = 'app_permission'
                   and policyname = 'exec can manage app_permission') then
    create policy "exec can manage app_permission"
      on app_permission for all to authenticated
      using (app_user_role() = 'exec')
      with check (app_user_role() = 'exec');
  end if;

  if not exists (select 1 from pg_policies
                 where tablename = 'app_role_permission'
                   and policyname = 'authenticated can read app_role_permission') then
    create policy "authenticated can read app_role_permission"
      on app_role_permission for select to authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies
                 where tablename = 'app_role_permission'
                   and policyname = 'exec can manage app_role_permission') then
    create policy "exec can manage app_role_permission"
      on app_role_permission for all to authenticated
      using (app_user_role() = 'exec')
      with check (app_user_role() = 'exec');
  end if;

  if not exists (select 1 from pg_policies
                 where tablename = 'app_module'
                   and policyname = 'authenticated can read app_module') then
    create policy "authenticated can read app_module"
      on app_module for select to authenticated using (true);
  end if;

  if not exists (select 1 from pg_policies
                 where tablename = 'app_module'
                   and policyname = 'exec can manage app_module') then
    create policy "exec can manage app_module"
      on app_module for all to authenticated
      using (app_user_role() = 'exec')
      with check (app_user_role() = 'exec');
  end if;

  -- Decisions are visible to whoever may approve in that area, and writable
  -- only by someone holding the matching approve permission. decided_by is
  -- pinned to the caller so a decision cannot be attributed to someone else.

  if not exists (select 1 from pg_policies
                 where tablename = 'platform_decision'
                   and policyname = 'approvers can read platform_decision') then
    create policy "approvers can read platform_decision"
      on platform_decision for select to authenticated
      using (app_user_role() in ('exec', 'dept_head') or decided_by = auth.uid());
  end if;

  if not exists (select 1 from pg_policies
                 where tablename = 'platform_decision'
                   and policyname = 'approvers can record a platform_decision') then
    create policy "approvers can record a platform_decision"
      on platform_decision for insert to authenticated
      with check (
        decided_by = auth.uid()
        and (
          (kind = 'timesheet' and app_user_has_permission('workload:approve'))
          or (kind = 'leave' and app_user_has_permission('hr:leave:approve'))
          or (kind = 'budget' and app_user_has_permission('projects:write'))
        )
      );
  end if;
end $$;

-- Decisions are an audit trail: no update, no delete policy, deliberately.
-- Reversing a decision means recording a new one.


-- ===========================================================================
-- 4. Seed data
-- ===========================================================================

-- Module registry. is_live=false is the default and the safe one: a module
-- appears here as soon as we start on it, but its tile stays hidden until it
-- is actually usable. Flipping is_live is the launch switch -- no deploy.
insert into app_module (module_key, display_name, tagline, href, accent, is_live, sort_order) values
  ('hub',      'HSE Hub',            'Analytics and approvals for leads',      '/',           '#91C2B7', true,  10),
  ('projects', 'Project Management', 'Projects, tasks, boards, milestones',    '/projects',   '#F0A868', true,  20),
  ('time',     'Time Tracking',      'Clock in, billable hours, services',     '/timesheets', '#7FB5D5', true,  30),
  ('hr',       'HSE HR',             'Leave, absences, contracts, clocking',   null,          '#C08FD0', false, 40),
  ('crm',      'CRM',                'Deals, pipeline, companies',             null,          '#D08F8F', false, 50)
on conflict (module_key) do nothing;

-- Canonical permission catalogue. These 22 keys are the ones
-- src/lib/permissions.ts checks, and check-permissions-rls.mjs asserts the two
-- lists stay in step -- adding a key to one without the other fails that gate.
insert into app_permission
  (permission_key, display_name, resource, action, description, module_key, sort_order) values
  ('overview:read',        'View Business Overview',     'overview',   'read',        'Access the executive KPI overview page',       'hub',      10),
  ('overview:export',      'Export Overview Data',       'overview',   'export',      'Download CSV/PDF exports from the overview',  'hub',      11),

  ('people:read_own',      'View Own Profile',           'people',     'read_own',    'See your own person record',                  'hub',      20),
  ('people:read_dept',     'View Department People',     'people',     'read_dept',   'See all people in your department',           'hub',      21),
  ('people:read_all',      'View All People',            'people',     'read_all',    'See every person record company-wide',        'hub',      22),
  ('people:write',         'Edit People Records',        'people',     'write',       'Create and update person records',            'hub',      23),

  ('projects:read_own',    'View Own Projects',          'projects',   'read_own',    'See projects you are assigned to',            'projects', 30),
  ('projects:read_dept',   'View Department Projects',   'projects',   'read_dept',   'See all projects in your department',         'projects', 31),
  ('projects:read_all',    'View All Projects',          'projects',   'read_all',    'See every project company-wide',              'projects', 32),
  ('projects:write',       'Edit Project Records',       'projects',   'write',       'Create and update project records',           'projects', 33),

  ('timesheets:read_own',  'View Own Timesheets',        'timesheets', 'read_own',    'See your own time entries',                   'time',     40),
  ('timesheets:read_dept', 'View Department Timesheets', 'timesheets', 'read_dept',   'See all timesheets in your department',       'time',     41),
  ('timesheets:read_all',  'View All Timesheets',        'timesheets', 'read_all',    'See every timesheet company-wide',            'time',     42),
  ('timesheets:write',     'Submit Timesheets',          'timesheets', 'write',       'Create and submit your own time entries',     'time',     43),

  ('workload:read',        'View Workload Board',        'workload',   'read',        'Access the team lead booking board',          'hub',      50),
  ('workload:approve',     'Approve Bookings',           'workload',   'approve',     'Approve or reject booking requests',          'hub',      51),

  ('admin:users:read',     'View User Accounts',         'admin',      'users:read',  'List all provisioned user accounts',          'hub',      60),
  ('admin:users:write',    'Manage User Accounts',       'admin',      'users:write', 'Invite, edit, deactivate user accounts',      'hub',      61),
  ('admin:roles:read',     'View Role Permissions',      'admin',      'roles:read',  'See which permissions each role has',         'hub',      62),
  ('admin:roles:write',    'Edit Role Permissions',      'admin',      'roles:write', 'Grant or revoke permissions per role',        'hub',      63),

  ('sync:read',            'View Sync Status',           'sync',       'read',        'See data freshness indicators in the sync bar','hub',      70),
  ('sync:trigger',         'Trigger Manual Sync',        'sync',       'trigger',     'Force a data refresh from external systems',  'hub',      71)
on conflict (permission_key) do nothing;

-- Default permission sets per role, matching the model already in the app:
-- exec everything; dept_head all dept reads + approvals but no roles:write;
-- project_manager own+dept reads; employee own reads + own timesheet writes.
insert into app_role_permission (role_key, permission_key) values
  ('exec', 'overview:read'), ('exec', 'overview:export'),
  ('exec', 'people:read_own'), ('exec', 'people:read_dept'), ('exec', 'people:read_all'), ('exec', 'people:write'),
  ('exec', 'projects:read_own'), ('exec', 'projects:read_dept'), ('exec', 'projects:read_all'), ('exec', 'projects:write'),
  ('exec', 'timesheets:read_own'), ('exec', 'timesheets:read_dept'), ('exec', 'timesheets:read_all'), ('exec', 'timesheets:write'),
  ('exec', 'workload:read'), ('exec', 'workload:approve'),
  ('exec', 'admin:users:read'), ('exec', 'admin:users:write'), ('exec', 'admin:roles:read'), ('exec', 'admin:roles:write'),
  ('exec', 'sync:read'), ('exec', 'sync:trigger'),

  ('dept_head', 'overview:read'),
  ('dept_head', 'people:read_own'), ('dept_head', 'people:read_dept'),
  ('dept_head', 'projects:read_own'), ('dept_head', 'projects:read_dept'),
  ('dept_head', 'timesheets:read_own'), ('dept_head', 'timesheets:read_dept'), ('dept_head', 'timesheets:write'),
  ('dept_head', 'workload:read'), ('dept_head', 'workload:approve'),
  ('dept_head', 'admin:users:read'), ('dept_head', 'admin:roles:read'),
  ('dept_head', 'sync:read'),

  ('project_manager', 'overview:read'),
  ('project_manager', 'people:read_own'), ('project_manager', 'people:read_dept'),
  ('project_manager', 'projects:read_own'), ('project_manager', 'projects:read_dept'),
  ('project_manager', 'timesheets:read_own'), ('project_manager', 'timesheets:read_dept'), ('project_manager', 'timesheets:write'),
  ('project_manager', 'workload:read'),
  ('project_manager', 'sync:read'),

  ('employee', 'people:read_own'),
  ('employee', 'projects:read_own'),
  ('employee', 'timesheets:read_own'), ('employee', 'timesheets:write'),
  ('employee', 'sync:read')
on conflict (role_key, permission_key) do nothing;

-- Re-tag module ownership for any environment where an older version of this
-- was applied by hand: those rows predate module_key and would all carry the
-- 'hub' default, which would put Projects and Time permissions on the wrong
-- tile. The INSERT above sets it correctly for a fresh database; this UPDATE
-- fixes an existing one. Both paths must end in the same state.
update app_permission set module_key = 'projects' where resource = 'projects';
update app_permission set module_key = 'time'     where resource = 'timesheets';
update app_permission set module_key = 'hub'
  where resource in ('overview', 'people', 'workload', 'admin', 'sync');

-- Module-scoped permissions for the modules that don't exist yet. Seeding them
-- now means the HR module's access model is reviewable before a line of HR code
-- is written, and the tile stays hidden regardless because app_module.is_live
-- is false for 'hr'. Granting these to a role is therefore safe today.
insert into app_permission
  (permission_key, display_name, resource, action, description, module_key, sort_order) values
  ('hr:leave:read',      'View Leave Requests',   'leave',    'read',    'See leave and absence requests',           'hr',   80),
  ('hr:leave:write',     'Request Leave',         'leave',    'write',   'Submit your own leave requests',           'hr',   81),
  ('hr:leave:approve',   'Approve Leave',         'leave',    'approve', 'Approve or reject leave requests',         'hr',   82),
  ('hr:contract:read',   'View Contracts',        'contract', 'read',    'See employment contract details',          'hr',   83),
  ('hr:clocking:write',  'Clock In and Out',      'clocking', 'write',   'Record working-time clock events',         'hr',   84),
  ('crm:deal:read',      'View Deals',            'deal',     'read',    'See CRM deals and pipeline stages',        'crm',  90),
  ('crm:deal:write',     'Edit Deals',            'deal',     'write',   'Create and update CRM deals',              'crm',  91)
on conflict (permission_key) do nothing;

-- Give the new keys to roles consistent with the existing model: everyone may
-- request their own leave, leads may approve within their scope, execs get all.
insert into app_role_permission (role_key, permission_key) values
  ('exec', 'hr:leave:read'), ('exec', 'hr:leave:write'), ('exec', 'hr:leave:approve'),
  ('exec', 'hr:contract:read'), ('exec', 'hr:clocking:write'),
  ('exec', 'crm:deal:read'), ('exec', 'crm:deal:write'),
  ('dept_head', 'hr:leave:read'), ('dept_head', 'hr:leave:write'),
  ('dept_head', 'hr:leave:approve'), ('dept_head', 'hr:clocking:write'),
  ('project_manager', 'hr:leave:read'), ('project_manager', 'hr:leave:write'),
  ('project_manager', 'hr:clocking:write'),
  ('employee', 'hr:leave:write'), ('employee', 'hr:clocking:write')
on conflict (role_key, permission_key) do nothing;


-- ===========================================================================
-- 5. Verification -- this should return all green after a successful run.
-- ===========================================================================

select
  (select count(*) from app_permission)                          as permissions,   -- expect 29
  (select count(*) from app_role_permission)                     as role_grants,   -- expect 66
  (select count(*) from app_module)                              as modules,       -- expect 5
  (select count(*) from app_module where is_live)                as live_modules,  -- expect 3
  (select count(*) from pg_policies
    where tablename in ('app_permission','app_role_permission',
                        'app_module','platform_decision'))       as policies,      -- expect 8
  app_user_has_permission('overview:read')                       as rpc_works;     -- expect f (no session in SQL Editor)
