-- ---------------------------------------------------------------------------
-- SUPERSEDED — this migration's contents now live in supabase/schema.sql (§3b).
--
-- Kept as a file rather than deleted because it is referenced in
-- docs/architecture/PLATFORM-ARCHITECTURE.md and in earlier commit messages as
-- "the migration to apply", so a reader following those will land here.
--
-- Why it moved: this file being separate is exactly what caused the outage it
-- was meant to prevent. The permission tables were absent from the live
-- database while every other table was present, because schema.sql got applied
-- and this did not — /admin/roles silently redirected every user, including
-- exec, to the home page with no error anywhere. A fresh environment must not
-- be able to come up missing part of its own access-control system.
--
-- WHAT TO RUN NOW: apply supabase/schema.sql in the SQL Editor. It is
-- idempotent (create table if not exists / create or replace function /
-- on conflict do nothing), so running it against the existing live database
-- adds the permission objects without disturbing anything already there.
--
-- The one caveat: policies use plain `create policy`, which errors if the
-- policy already exists. If you hit that, it means the object was already
-- created; the error is safe to skip.
-- ---------------------------------------------------------------------------

-- Intentionally empty. See schema.sql §3b.
